# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: public-repo
    type: github
    endpoint: github-demo-service-connection
    name: Azure/OSS-Demo-Public

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: public-repo
  persistCredentials: true
- script: |
    git checkout 9ea9e1173a83931204e96769942d3674b037fa8d
    echo
    echo "***************"
    echo QEMU Tests ran!
    echo "***************"
    echo
    echo Git Log to show that we actually use the merge commit:
    echo
    git log --format=oneline origin/main..HEAD
    git status
  displayName: 'Run QEMU Tests'
  workingDirectory: $(Build.SourcesDirectory)

