name: ManualBuild


on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/msazuresphere/OSS-Demo-Public
            azure-pipeline-name: 'Azure.OSS-Demo-Public QEMU BVTs'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
